INSERT INTO `student`(`name`, `course`, `score`) VALUES ('张三', '语文', 79);
INSERT INTO `student`(`name`, `course`, `score`) VALUES ('张三', '数学', 90);
INSERT INTO `student`(`name`, `course`, `score`) VALUES ('张三', '英语', 77);
INSERT INTO `student`(`name`, `course`, `score`) VALUES ('李四', '语文', 98);
INSERT INTO `student`(`name`, `course`, `score`) VALUES ('李四', '数学', 100);
INSERT INTO `student`(`name`, `course`, `score`) VALUES ('王五', '语文', 87);
INSERT INTO `student`(`name`, `course`, `score`) VALUES ('王五', '数学', 76);
INSERT INTO `student`(`name`, `course`, `score`) VALUES ('王五', '英语', 56);
INSERT INTO `student`(`name`, `course`, `score`) VALUES ('李四', '英语', 89);
